default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: time_tracker_development

test:
  <<: *default
  database: time_tracker_test

production: &production
  <<: *default
  database: time_tracker_production
  username: time_tracker
  password: test

staging:
  <<: *production
