default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: fjord_development

test:
  <<: *default
  database: fjord_test

production: &production
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

review:
  <<: *production

staging:
  <<: *production
